package main

import "testing"

func TestTreeIsEmpty(t *testing.T) {
    t.Error("Fail on purpose")
}
